const CHANNEL_REWARDS = {
  SPORTS: "CHAMPIONS_LEAGUE_FINAL_TICKET",
  KIDS: null,
  MUSIC: "KARAOKE_PRO_MICROPHONE",
  NEWS: null,
  MOVIES: "PIRATES_OF_THE_CARIBBEAN_COLLECTION",
};

const ELIGIBILITY = {
  CUSTOMER_ELIGIBLE: "CUSTOMER_ELIGIBLE",
  CUSTOMER_INELIGIBLE: "CUSTOMER_INELIGIBLE",
};

module.exports = { CHANNEL_REWARDS, ELIGIBILITY };
